### ISSUE TITLE
FEATURE REQUEST: Daily Sensor

### ISSUE THREAD

**Issue by Scags104** [alexander0042/pirate-weather-hacs#1]
Thank you for this! 

Would be great to have a secondary sensor when popped into a weather card that shows daily forecast as easily as it shows hourly. Currently difficult to manipulate the current sensor as it would cause me to have to create a few template sensors to rip out the data which only goes about 2 days forward. Makes sense this would be separate.

**Comment by alexander0042** [comment]
Thanks for the suggestion, I want to keep improving this integration, so I appreciate all the ideas!

That being said, I think this might already have that capability, at least if you're using it as a sensor? Since this (at this point anyway) identical to the built in dark sky sensor, their docs (which should have [linked to](https://www.home-assistant.io/integrations/weather.darksky/#mode)!) suggest that you can add a "forecast" parameter to your config file, and then it should return the daily data?

If you're using it as a "weather" integration, the docs say that adding a "mode" condig as daily should provide daily data. However, for some reason that throws an error with the standard Dark Sky API. I've pushed a tiny commit that fixes this with PirateWeather though, so if this is what you were looking for, you should be set! 

![image](https://user-images.githubusercontent.com/26213938/118543903-ea250d80-b722-11eb-8225-a7b0a4955cda.png)

**Comment by Scags104** [comment]
Thank you! This works!

Needed to double up on my yaml so I could specify the mode and have both daily and hourly functionality (for anyone else who may stumble here looking for similar answers)
