### ISSUE TITLE
[Error] Unable to connect to Dark Sky. 502 Server Error: Bad Gateway 

### ISSUE THREAD

**Issue by 1darklyte** [alexander0042/pirate-weather-hacs#3]
This error started popping up today : https://prnt.sc/134o0kk

` Logger: custom_components.darksky.weather
Source: custom_components/darksky/weather.py:278
Integration: darksky (documentation, issues)
First occurred: 1:47:05 PM (1 occurrences)
Last logged: 1:47:05 PM
Unable to connect to Dark Sky. 502 Server Error: Bad Gateway for url: [URL Here]

**Comment by 1darklyte** [comment]
as of 2:22pm EST seems to be back online

**Comment by alexander0042** [comment]
I saw this too! I'd been noticing the occasional 502 in my instance, but I think I fixed that by changing the file system to burst mode instead of provisioned. However, today around then it started returning 502 for every request.

I traced this issue seems to have been in a bad alerts.json file from the National Weather Service. Either their server had a formatting issue, or my downloader cut out. I've added some more error handing code to handle this gracefully now, so shouldn't happen again!

Thanks for the report, it really helps fix things when these edge cases are bright up!
